# Change these first
owner: ZeusTanks # Your GitHub organization or username, where this repository lives
repo: ztanks-status # The name of this repository

sites:
  - name: Website
    url: https://zeustanks.online
  - name: Zeus Tanks server
    check: "tcp-ping"
    url: $SERVER_IP
    port: 2351
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zeustanks.online
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/icons/1286862621425008740/2430b85419192da5e6c04a5b660f197d.webp?size=1024&format=webp
  name: ZeusTanks Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Website
      href: https://zeustanks.online
    - title: Discord
      href: https://discord.gg/fUVc5VSSeV
    - title: Status
      href: /
skipDeleteIssues: true
i18n:
  footer: ""
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
